# Generated by Django 5.2.4 on 2025-08-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_volume',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
    ]
